### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Manguil** [ray-pH/Nabla-TypeMath-android#1]
The application looks great, but for the moment, replacing the order with the text you have chosen does not work.
Thanks in advance for your help

**Comment by ray-pH** [comment]
Do you mean the "custom commands/keyword" that doesn't work?

**Comment by Manguil** [comment]
No all command

**Comment by ray-pH** [comment]
well, that's a bug. Can you tell me information about your device.. android version, device model, etc.

**Comment by Manguil** [comment]
Android 9.1, Honor 9 lite, what else do you want to know?

**Comment by Manguil** [comment]
and I noticed that I had to give permission every time I restarted the phone to activate the service
