### ISSUE TITLE
mathbb doesn't work in LaTeX mode, even if it's used as an example in the help

### ISSUE THREAD

**Issue by quexpexx** [ray-pH/Nabla-TypeMath-android#2]
I use LaTeX mode. My initial and end strings are both `$$`.  
Whenever I type `$$\mathbb{R}$$` (or any other letter in place of R, R is just used as an example in the help), after hitting space, it just gets substituted with `\mathbb{R}`, rather than ℝ.  
I'm not sure what the relevant information about my system that I need to provide this, but just to say: I'm on the latest Play Store version of the app. I downloaded it from F-Droid initially, but it didn't seem to be the latest version (Play Store is 1.3, F-Droid is 1.2).  
If you need any other info about my system, just ask, and I'll try to provide it. Thank you.

**Comment by ray-pH** [comment]
Oh yeah, there is a bug in the LaTeX mode. Will look into it.. Thanks for the report.

**Comment by ray-pH** [comment]
Fixed in v1.3.1

**Comment by quexpexx** [comment]
After a bit of pain of not being able to get the service to work at all after the update, I ended up clearing cache. I can confirm my issue with LaTeX mode is fixed now. Thanks.
