### ISSUE TITLE
Custom Commands Break Things

### ISSUE THREAD

**Issue by SpookedByRoaches** [ray-pH/Nabla-TypeMath-android#7]
When I try to add custom commands on the app, they don't work and I can't edit them anymore. When I click edit custom commands, it restarts.

This happens on both the F-Droid and the Github release version 1.3.3.
On a Pixel 6 pro.

**Comment by ray-pH** [comment]
The app break only after you add the command? Does uninstalling and reinstalling it again helps?

**Comment by ray-pH** [comment]
Oh wait, there's something wrong with the apk version. But for some reason, the one in google play works fine. I will look into it

**Comment by SpookedByRoaches** [comment]
> The app break only after you add the command? Does uninstalling and reinstalling it again helps?

Yeah I tried reinstalling it and the issue persists. When I delete the storage, everything goes back to normal but the commands are removed (which is expected). However, when I add the commands again, the issue comes back. 

If you can't reproduce, I can try to get the logs which may help.

**Comment by ray-pH** [comment]
I've reproduced it in my own device

```
FATAL EXCEPTION: main
Process: com.ph.nabla_typemath, PID: 2688
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ph.nabla_typemath/com.ph.nabla_typemath.CustomCommand}: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
```

something to do with the code shrinkers, working on it

**Comment by ray-pH** [comment]
released a new version that fixes the bug. Apparently, there are more bugs related to how the app handles user settings which was introduced when we updated the app to the new Android SDK version.

Let me know if there are still problems
